# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'AzureRmPipeline-conn'
    subscriptionName: '9f6ec589-a4fc-4ce7-aa65-0eb91940c609'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ukra-rg'
    location: 'ukwest'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'
- task: AzureResourceGroupDeployment@2
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'AzureRmPipeline-conn'
    subscriptionName: '9f6ec589-a4fc-4ce7-aa65-0eb91940c609'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ukra-rg'
    location: 'ukwest'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureVnet/azuredeploy.json'
    deploymentMode: 'Incremental'



